export const meisterschaftenListe = [
  "Akrobatik",
  "Alchemie",
  "Anführen",
  "Arkane Kunde",
  "Athletik",
  "Darbietung",
  "Diplomatie",
  "Edelhandwerk",
  "Empathie",
  "Entschlossenheit",
  "Fingerfertigkeit",
  "Geschichte und Mythen",
  "Handwerk",
  "Heilkunde",
  "Heimlichkeit",
  "Jagdkunst",
  "Länderkunde",
  "Naturkunde",
  "Redegewandtheit",
  "Schlösser und Fallen",
  "Schwimmen",
  "Seefahrt",
  "Straßenkunde",
  "Tierführung",
  "Überleben",
  "Wahrnehmung",
  "Zähigkeit",
];

export const staerkenListe = [
  "Asket",
  "Attraktivität",
  "Aura des:der Auserwählten",
  "Ausdauernd",
  "Bastler:in",
  "Beistand in der Not",
  "Dämmersicht",
  "Einen Schritt voraus",
  "Empath:in",
  "Entfernungssinn",
  "Erhöhte Fokusregeneration",
  "Erhöhte Lebensregeneration",
  "Erhöhter Fokuspool",
  "Erwählte:r der Felswesen",
  "Erwählte:r der Feuerwesen",
  "Erwählte:r der Geisterwesen",
  "Erwählte:r der Götterdiener",
  "Erwählte:r der Lichtwesen",
  "Erwählte:r der Naturwesen",
  "Erwählte:r der Schattenwesen",
  "Erwählte:r der Untoter",
  "Erwählte:r der Wasserwesen",
  "Erwählte:r der Windwesen",
  "Feensinn",
  "Feine Nase",
  "Flink",
  "Gefahrensinn",
  "Gelenkig",
  "Geruchsleser:in",
  "Gesellig",
  "Giftresistenz",
  "Gleichgewichtssinn",
  "Greifschwanz",
  "Gutes Gedächtnis",
  "Heiliges Mal",
  "Hitzeresistenz",
  "Hoher Geistiger Widerstand",
  "Hoher Körperlicher Widerstand",
  "Instinkt des Jägers/der Jägerin",
  "Kälteresistenz",
  "Kind der Lüge",
  "Kind der Natur",
  "Kind der Ordnung",
  "Kind der Vorsehung",
  "Kind der Weisheit",
  "Kind des Lebens",
  "Kind des Lichtes",
  "Kind des Todes",
  "Kind des Windes",
  "Konzentrationsstärke",
  "Krankheitsresistenz",
  "Kulturkunde",
  "Lastesel",
  "Literat:in",
  "Natürliche Waffe",
  "Natürlicher Rüstungsschutz",
  "Orientierungssinn",
  "Priester:in",
  "Robust 1",
  "Robust 2",
  "Robust 3",
  "Scharfe Sicht",
  "Scharfes Gehör",
  "Schild des Glaubens",
  "Schmerzresistenz",
  "Soziales Gespür",
  "Stabile Magie",
  "Tierfreund:in",
  "Tiervertrauter",
  "Verbesserte Initiative",
  "Weltgewandt",
  "Zäh",
  "Zielstrebig",
  "Zusätzliche Splitterpunkte",
];

export const KampffertigkeitenListe = [
  "Handgemenge",
  "Klingenwaffen",
  "Hiebwaffen",
  "Kettenwaffen",
  "Schusswaffen",
  "Stangenwaffen",
  "Wurfwaffen",
];

export const magiefertigkeitenListe = [
  { name: "bannmagie", attributes: ["mystik", "willenskraft"] },
  { name: "beherrschungsmagie", attributes: ["mystik", "willenskraft"] },
  { name: "bewegungsmagie", attributes: ["mystik", "beweglichkeit"] },
  { name: "erkenntnismagie", attributes: ["mystik", "verstand"] },
  { name: "felsmagie", attributes: ["mystik", "konstitution"] },
  { name: "feuermagie", attributes: ["mystik", "ausstrahlung"] },
  { name: "heilungsmagie", attributes: ["mystik", "ausstrahlung"] },
  { name: "illusionsmagie", attributes: ["mystik", "ausstrahlung"] },
  { name: "kampfmagie", attributes: ["mystik", "staerke"] },
  { name: "lichtmagie", attributes: ["mystik", "ausstrahlung"] },
  { name: "naturmagie", attributes: ["mystik", "ausstrahlung"] },
  { name: "schattenmagie", attributes: ["mystik", "intuition"] },
  { name: "schicksalsmagie", attributes: ["mystik", "ausstrahlung"] },
  { name: "schutzmagie", attributes: ["mystik", "ausstrahlung"] },
  { name: "stärkungsmagie", attributes: ["mystik", "staerke"] },
  { name: "todesmagie", attributes: ["mystik", "verstand"] },
  { name: "verwandlungsmagie", attributes: ["mystik", "konstitution"] },
  { name: "wassermagie", attributes: ["mystik", "intuition"] },
  { name: "windmagie", attributes: ["mystik", "verstand"] },
];
